version: '3.9'

services:
  postgres:
    image: postgres:15-alpine  
    container_name: postgres_tododb
    ports:
      - "5435:5432"     
    environment:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"  
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data  

volumes:
  postgres_data:
  redis_data:
